import React from "react";
import { withRouter } from "next/router";
import Head from "next/head";
//STORES , COMPONETS AND FROMS

//INITIALISE

//PAGE
class LayoutComponet extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
  }
  componentDidMount() {}
  render() {
    return (
      <>
        <Head>
          <title>Pharmacy CMS</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="./assets/logo.jpg" />
        </Head>
        <main className="min-h-full " style={{ height: "100vh" }}>
          {" "}
          {this.props.children}
        </main>
      </>
    );
  }
}

const Layout = withRouter(LayoutComponet);

export default Layout;
